/users/PAS1383/osu10171/SurenRepo/iceberg

The following have been reloaded with a version change:
  1) python/2.7.8 => python/2.7.latest

Traceback (most recent call last):
  File "/usr/local/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 48, in main
    activate.main()
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/cli/activate.py", line 135, in main
    conda.install.symlink_conda(prefix, root_dir, shell)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/install.py", line 596, in symlink_conda
    symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/install.py", line 610, in symlink_conda_hlp
    os.remove(prefix_file)
OSError: [Errno 2] No such file or directory: '/users/PAS1383/osu10171/.conda/envs/local/bin/conda'

-----------------------
Resources requested:
nodes=1:ppn=1
mem=16gb
-----------------------
Resources used:
cput=00:00:01
walltime=00:00:06
mem=0.000 GB
vmem=0.000 GB
-----------------------
Resource units charged (estimate):
0.000 RUs
-----------------------
